
CREATE TABLE folder (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);


ALTER TABLE note
  ADD COLUMN
  id_folder INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL;


    -- to allow nulls in NOTE id_folder if a folder with related notes is deleted:
    -- id_folder INTEGER REFERENCES folder(id) ON DELETE SET NULL


    -- to Cascade Delete all related notes when a folder is deleted:
    -- id_folder INTEGER REFERENCES folder(id) ON DELETE CASCADE NOT NULL,
